# Generated by Django 5.1 on 2024-09-09 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('PageCount', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('isbn_number', models.CharField(max_length=127, unique=True)),
                ('price', models.FloatField()),
                ('avg_review', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='core.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='core.genre')),
            ],
        ),
    ]
